name: Python Lint 

on: 
    workflow_dispatch:

jobs:
    validate: 
        runs-on: ubuntu-latest 
        steps: 
            - name: Checkout Code 
              uses: actions/checkout@v5
            
            - name: Set Up Python 
              uses: actions/setup-python@v5

            - name: Installing all the packages and librarires 
              run: pip install -r requirements.txt

            - name: Installed the Linter and running
              run: flake8 . 