name: Python Matrix Strategy 

on:
    push:
        branches: [main]

jobs:
    Checkversion: 
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.9","3.10","3.11", "3.12", "3.13", "3.14"]

        steps:
            - name: Code Checkout 
              uses: actions/checkout@v5
            
            - name: Setup Python ${{matrix.python-version}}
              uses: actions/setup-python@v5
              with: ${{matrix.python-version}}

            - name: Install All Packages 
              run: pip install -r requirements.txt

            - name: Run Linter
              run: flake8 .
                  


