name: Deploy Flask App 
on:
    workflow_dispatch:
    workflow_run: 
        workflows: ["Docker Build and Push"]
        branches: [main]
        types:
            - completed

jobs:
    deploy:
        runs-on: self-hosted
        env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Deploy with Docker Compose
              run: docker compose down && docker compose up -d --build --force-recreate --pull always

            