name: Docker Lint
on:
    workflow_call:

jobs:
    docker-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Lint Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: ./Dockerfile